### ISSUE TITLE
Finish Project slides

### ISSUE THREAD

**Issue by fnriv** [cse110-sp23-group3/8-ball#24]
Jiaen's suggested layout for the slides:

- [x] Overview: briefly introduction
- [ ] Functionality and Usage Instructions (Display the website)
- [ ] Workflow of this assignment
- [ ] How we apply the AI tools
- [ ] The problem we found during using the AI tools
- [ ] How we solve these problems

slides: https://docs.google.com/presentation/d/1d1kxv6KMosrcdN_mtuxBd-KzHd8hcqui-LANHAJvJoE/edit?usp=sharing 

If you worked on code and can leave some sort of comment or reflection regarding one of these points that I can add, please do (you can leave a comment here). As far as I know from a quick look this includes @nsyousef @lemangomeister @phuanh004 @yujiaen1999 @dolivares11 @ChayPark

**Comment by nsyousef** [comment]
I played around with the AI and left some info about my experiment in issue #7. Some key points that I found from that are:

1) ChatGPT is good for making basic apps, but it may have trouble if you try to ask it to make a large app with complex requirements in one command.
2) To solve the above problem, you can ask it to build a basic app and then in follow-ups tell it to add features. Sometimes when it adds features, the code can be copy-pasted and it works, but other times new code is not consistent with old code and you have to play with it to get it to work.
3) I asked ChatGPT how to create unit tests in Javascript with no external frameworks and it gave me a basic response with some code as an example. However, it was not very detailed and did not give a complete picture of how the unit testing works.
4) To figure out how to make the "Ask" button disable itself when the animation/music are playing, I asked ChatGPT to create a basic app with a button, where when you click it, the button is greyed out for 5 seconds and then becomes enabled again. I was able to use that to figure out how to disable the button in our app when the animation plays.
5) For image-generating AI, the images it generates are usually pretty good, but text in the images is often mangled and unreadable. You can't ask the image AI to incorporate text into the image since it does not understand complex shapes like that. It can make glyphs that sort of resemble text, but don't resemble English letters.
